### PR TITLE
fix placeholder issue

### PR DESCRIPTION
**Pull request by nilscox**
I got an issue with the placeholder, and apparently fixed it. I don't have much time to read the whole code, so feel free to merge this fix if it makes sens to you.

### CODE REVIEW

**Comment by tom-s** [comment]
Hi, what issue did you have exactly ?

**Comment by nilscox** [comment]
The item I am dragging is moving away, and an exception is thrown repeatedly:

```
react-drag-sortable.js:310 Uncaught TypeError: Cannot read property 'rank' of undefined
    at DragSortableList._movePlaceholder (react-drag-sortable.js:310)
    at DragSortableList._dragMove (react-drag-sortable.js:233)
    at Interactable.wrapper [as ondragmove] (index.js:3095)
    at Interactable.fire (interact.js:5014)
    at Interaction.dragMove (interact.js:1976)
    at Interaction.pointerMove (interact.js:1927)
    at HTMLDocument.<anonymous> (interact.js:3349)
```

So I guessed that assigning a value to `newPlaceholder` would fix the issue, and it did in my case.

I am using chromium with all extensions disabled: `Chromium 55.0.2883.87`.

**Comment by tom-s** [comment]
I couldn't reproduce the issue. However I updated the code to fix your issue (in a slightly different way). It's been published under version 1.0.1, you can see the PR here : https://github.com/tom-s/react-drag-sortable/pull/7

Please feel free to close the issue if it works for you

**Comment by nilscox** [comment]
Yes, this is fine now. Thanks!

**Pull request closed without merging**
